

all: szolancj
	-

dir=szolanc

szolancj: $(dir)/JatekSzerver.java $(dir)/GepiJatekos.java $(dir)/InteraktivKliens.java $(dir)/SzolancSzimulacio.java $(dir)/SzolancJatek.java
	javac $(dir)/JatekSzerver.java $(dir)/GepiJatekos.java $(dir)/InteraktivKliens.java $(dir)/SzolancSzimulacio.java $(dir)/SzolancJatek.java
